version: '2.1'
# volumes:
#   dbbackups:
#   postgis-data:

services:
    web:
        build: .
        command: gunicorn geodjango.wsgi:application --bind 0.0.0.0:8000 --workers 4
        ports:
            - 8000:8000
        volumes:
            - .:/code
        environment:
            - DB_TYPE=postgis
    db:
        image: kartoza/postgis:13-3.1
        volumes:
            - ./postgis-data:/var/lib/postgresql
            - ./dbbackups:/backups
        environment:
            # If you need to create multiple database you can add coma separated databases eg gis,data
            - POSTGRES_DB=gis
            - POSTGRES_USER=geodjango
            - POSTGRES_PASS=geo
            - ALLOW_IP_RANGE=0.0.0.0/0
            # Add extensions you need to be enabled by default in the DB. Default are the five specified below
            - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
        ports:
            - 25432:5432
        restart: on-failure
        healthcheck:
            test: "exit 0"
        
