# Generated by Django 3.1.7 on 2021-08-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='hyperlink',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mission',
            name='enemyaction',
            field=models.CharField(max_length=1024, verbose_name='ENEMYACTION'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='alt_weapon_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_class',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(max_length=255),
        ),
    ]
